language: node_js
node_js:
  - '4'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
script: "npm run test-travis"
# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
