language: node_js
node_js:
  - '6'
  - '8'
  - '10'
  - 'lts/*'
script:
  - npm run lint
  - npm test
# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
cache:
  directories:
    - node_modules
